import { useState, useEffect } from 'react';
import { FileSpreadsheet, Plus, Search, Download, Printer, Edit2, Trash2, X, Eye } from 'lucide-react';
import { Customer } from './CustomerList';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatKenyanNumber } from '../utils/numberFormat';
import { 
  addInvoice, 
  updateInvoice, 
  deleteInvoice, 
  subscribeToInvoices 
} from '../services/invoiceService';
import { 
  InventoryItem, 
  subscribeToInventoryItems,
  updateInventoryItem 
} from '../services/inventoryService';
import { addTransaction, updateAccountingTransactionForInvoice } from '../services/transactionService';
import { subscribeToCompanyDetails, CompanyDetails } from '../services/companyService';
import { 
  createInvoiceTransaction, 
  deletePaymentTrackingByReference,
  getTotalPaidForInvoice,
  updateInvoicePaymentTrackingAmount
} from '../services/paymentTrackingService';
import { collection, query, where, getDocs, deleteDoc, doc } from 'firebase/firestore';
import { db } from '../config/firebase';
import { useAuth } from '../contexts/AuthContext';


export interface InvoiceItem {
  itemCode: string;
  itemDescription: string;
  quantity: number;
  unitPrice: number;
  taxRate: number;
  amountExclTax: number;
  taxAmount: number;
  amountInclTax: number;
}

export interface Invoice {
  id: string;
  systemInvoiceNumber: string; // Auto-generated by system
  manualInvoiceNumber: string; // Manually entered
  date: string;
  customerName: string;
  customerPRN: string;
  invoiceFrom: {
    pin: string;
    name: string;
    address: string;
    mobile: string;
  };
  items: InvoiceItem[];
  taxableTotalAmount: number;
  totalTaxAmount: number;
  totalAmount: number;
  scuInformation: string;
  internalData: string;
  cuInvoiceNumber: string;
  status: 'draft' | 'issued';
  createdAt: string;
}

interface InvoiceManagementProps {
  customers: Customer[];
  bankAccounts?: { id: string; accountName: string; currentBalance: number; accountNumber: string; initialBalance: number }[];
}

export default function InvoiceManagement({ customers, bankAccounts = [] }: InvoiceManagementProps) {
  const { user } = useAuth();
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [inventoryItems, setInventoryItems] = useState<InventoryItem[]>([]);
  const [showAddForm, setShowAddForm] = useState(false);
  const [editingInvoice, setEditingInvoice] = useState<Invoice | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState<'all' | 'draft' | 'issued'>('all');
  const [saving, setSaving] = useState(false);
  const [printPreviewInvoice, setPrintPreviewInvoice] = useState<Invoice | null>(null);
  
  // Autocomplete suggestions state
  const [itemCodeSearchTerms, setItemCodeSearchTerms] = useState<Record<number, string>>({});
  const [showItemCodeDropdowns, setShowItemCodeDropdowns] = useState<Record<number, boolean>>({});
  
  // Company details state - now loaded from Firebase
  const [companyDetails, setCompanyDetails] = useState<CompanyDetails>({
    id: 'company',
    companyPIN: '',
    companyName: '',
    address: '',
    mobile: '',
    email: '',
    updatedAt: new Date().toISOString()
  });

  // Subscribe to company details from Firebase
  useEffect(() => {
    const unsubscribe = subscribeToCompanyDetails(
      (details) => {
        setCompanyDetails(details);
      },
      (error) => {
        console.error('Error subscribing to company details:', error);
      }
    );

    return () => unsubscribe();
  }, []);

  // Subscribe to invoices from Firebase
  useEffect(() => {
    const unsubscribe = subscribeToInvoices(
      (updatedInvoices) => {
        setInvoices(updatedInvoices);
      },
      (error) => {
        console.error('Error subscribing to invoices:', error);
      }
    );

    return () => unsubscribe();
  }, []);

  // Subscribe to inventory items from Firebase
  useEffect(() => {
    const unsubscribe = subscribeToInventoryItems(
      (items) => {
        setInventoryItems(items);
      },
      (error) => {
        console.error('Error subscribing to inventory items:', error);
      }
    );

    return () => unsubscribe();
  }, []);

  const [formData, setFormData] = useState({
    date: new Date().toISOString().split('T')[0],
    customerName: '',
    customerPRN: '',
    manualInvoiceNumber: '',
    invoiceFrom: {
      pin: companyDetails.companyPIN,
      name: companyDetails.companyName,
      address: companyDetails.address,
      mobile: companyDetails.mobile
    },
    items: [
      {
        itemCode: '',
        itemDescription: '',
        quantity: 1,
        unitPrice: 0,
        taxRate: 16,
      },
    ],
    status: 'draft' as 'draft' | 'issued',
  });

  // Update formData invoiceFrom when companyDetails changes
  useEffect(() => {
    setFormData(prev => ({ 
      ...prev, 
      invoiceFrom: {
        pin: companyDetails.companyPIN,
        name: companyDetails.companyName,
        address: companyDetails.address,
        mobile: companyDetails.mobile
      }
    }));
  }, [companyDetails]);

  // Generate sequential system invoice number
  const generateSystemInvoiceNumber = () => {
    const count = invoices.length + 1;
    return `INV-${String(count).padStart(6, '0')}`;
  };

  // Calculate item totals
  const calculateItemTotals = (quantity: number, unitPrice: number, taxRate: number) => {
    const amountExclTax = quantity * unitPrice;
    const taxAmount = (amountExclTax * taxRate) / 100;
    const amountInclTax = amountExclTax + taxAmount;
    return { amountExclTax, taxAmount, amountInclTax };
  };

  // Calculate invoice totals
  const calculateInvoiceTotals = () => {
    let taxableTotalAmount = 0;
    let totalTaxAmount = 0;
    let totalAmount = 0;

    formData.items.forEach((item) => {
      const { amountExclTax, taxAmount, amountInclTax } = calculateItemTotals(
        item.quantity,
        item.unitPrice,
        item.taxRate
      );
      taxableTotalAmount += amountExclTax;
      totalTaxAmount += taxAmount;
      totalAmount += amountInclTax;
    });

    return { taxableTotalAmount, totalTaxAmount, totalAmount };
  };

  // Get filtered items for dropdown based on search term
  const getFilteredItemCodes = (itemIndex: number) => {
    const searchTerm = itemCodeSearchTerms[itemIndex]?.toLowerCase() || '';
    if (!searchTerm) return [];
    return inventoryItems.filter(item => item.itemCode.toLowerCase().startsWith(searchTerm));
  };

  // Handle item code selection from dropdown
  const handleSelectItemCode = (itemIndex: number, inventoryItem: InventoryItem) => {
    const updatedItems = [...formData.items];
    updatedItems[itemIndex] = {
      ...updatedItems[itemIndex],
      itemCode: inventoryItem.itemCode,
      itemDescription: inventoryItem.itemName
    };
    setFormData({ ...formData, items: updatedItems });
    setShowItemCodeDropdowns({ ...showItemCodeDropdowns, [itemIndex]: false });
    setItemCodeSearchTerms({ ...itemCodeSearchTerms, [itemIndex]: inventoryItem.itemCode });
    
  };

  // Handle item change
  const handleItemChange = (index: number, field: string, value: string | number) => {
    const updatedItems = [...formData.items];
    
    // Special handling for item code changes
    if (field === 'itemCode' && typeof value === 'string') {
      // Don't trim or uppercase while typing - allow spaces
      updatedItems[index] = { ...updatedItems[index], itemCode: value };
      
      // Track search term for dropdown
      setItemCodeSearchTerms({ ...itemCodeSearchTerms, [index]: value });
      
      // Show dropdown if there's text
      if (value.trim()) {
        setShowItemCodeDropdowns({ ...showItemCodeDropdowns, [index]: true });
      } else {
        setShowItemCodeDropdowns({ ...showItemCodeDropdowns, [index]: false });
      }
      
      // Validate with trimmed and uppercased version
      const itemCodeToValidate = value.trim().toUpperCase();
      if (itemCodeToValidate) {
        const inventoryItem = inventoryItems.find(
          item => item.itemCode.toUpperCase() === itemCodeToValidate
        );
        
        if (inventoryItem) {
          // Auto-fill item name/description only (without available quantity)
          updatedItems[index].itemDescription = inventoryItem.itemName;
        }
      }
    } else {
      updatedItems[index] = { ...updatedItems[index], [field]: value };
    }
    
    setFormData({ ...formData, items: updatedItems });
  };

  // Add item row
  const addItemRow = () => {
    setFormData({
      ...formData,
      items: [
        ...formData.items,
        {
          itemCode: '',
          itemDescription: '',
          quantity: 1,
          unitPrice: 0,
          taxRate: 16,
        },
      ],
    });
  };

  // Remove item row
  const removeItemRow = (index: number) => {
    if (formData.items.length > 1) {
      const updatedItems = formData.items.filter((_, i) => i !== index);
      setFormData({ ...formData, items: updatedItems });
    }
  };

  // Get customer PRN
  const getCustomerPRN = (customerName: string) => {
    const customer = customers.find((c) => c.companyName === customerName);
    return customer ? customer.pin : '';
  };

  // Handle submit
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    setSaving(true);

    try {
      const { taxableTotalAmount, totalTaxAmount, totalAmount } = calculateInvoiceTotals();

      const invoiceItems: InvoiceItem[] = formData.items.map((item) => {
        const { amountExclTax, taxAmount, amountInclTax } = calculateItemTotals(
          item.quantity,
          item.unitPrice,
          item.taxRate
        );
        return {
          itemCode: item.itemCode,
          itemDescription: item.itemDescription,
          quantity: item.quantity,
          unitPrice: item.unitPrice,
          taxRate: item.taxRate,
          amountExclTax,
          taxAmount,
          amountInclTax,
        };
      });

      const newInvoice: Invoice = {
        id: editingInvoice?.id || Date.now().toString(),
        systemInvoiceNumber: editingInvoice?.systemInvoiceNumber || generateSystemInvoiceNumber(),
        manualInvoiceNumber: formData.manualInvoiceNumber,
        date: formData.date,
        customerName: formData.customerName,
        customerPRN: formData.customerPRN || getCustomerPRN(formData.customerName),
        invoiceFrom: formData.invoiceFrom,
        items: invoiceItems,
        taxableTotalAmount,
        totalTaxAmount,
        totalAmount,
        scuInformation: '',
        internalData: '',
        cuInvoiceNumber: editingInvoice?.cuInvoiceNumber || generateSystemInvoiceNumber(),
        status: formData.status,
        createdAt: editingInvoice?.createdAt || new Date().toISOString(),
      };

      if (editingInvoice) {
        const oldStatus = editingInvoice.status;
        const newStatus = formData.status;
          const oldAmount = editingInvoice.totalAmount;
          const newAmount = totalAmount;
        
        console.log(`=== Updating Invoice: ${editingInvoice.systemInvoiceNumber} ===`);
        console.log(`Old Status: ${oldStatus}, New Status: ${newStatus}`);
                console.log(`Old Amount: ${oldAmount}, New Amount: ${newAmount}`);
        
                // Validate: Check if new amount is less than total paid
                if (oldStatus === 'issued' && newStatus === 'issued' && newAmount < oldAmount) {
                  const totalPaid = await getTotalPaidForInvoice(editingInvoice.systemInvoiceNumber);
                  if (newAmount < totalPaid) {
                    const confirmEdit = window.confirm(
                      `WARNING: New invoice amount (${newAmount.toFixed(2)}) is less than total paid (${totalPaid.toFixed(2)}).\n\n` +
                      `This will create an overpayment of ${(totalPaid - newAmount).toFixed(2)}.\n\n` +
                      `Do you want to continue?`
                    );
                    if (!confirmEdit) {
                      setSaving(false);
                      return;
                    }
                  }
                }
        
        // Update existing invoice in Firebase
        await updateInvoice(editingInvoice.id, newInvoice);
          console.log('✓ Invoice updated in database');
        
        // Handle inventory updates based on status changes AND quantity changes
        
        // Case 1: Status changed from issued to draft - REVERSE all inventory
        if (oldStatus === 'issued' && newStatus === 'draft') {
          console.log('Reversing inventory changes (issued/paid → draft/cancelled)');
          
          for (const item of editingInvoice.items) {
            const inventoryItem = inventoryItems.find(
              inv => inv.itemCode.toUpperCase() === item.itemCode.toUpperCase()
            );
            
            if (inventoryItem) {
              const currentInBalance = Number(inventoryItem.inBalance || 0);
              const currentOutBalance = Number(inventoryItem.outBalance || 0);
              
              // Remove the OLD quantity from outBalance
              const newOutBalance = Math.max(0, currentOutBalance - item.quantity);
              const newAvailableQuantity = currentInBalance - newOutBalance;
              const newTotalBalance = newAvailableQuantity;
              
              console.log(`  Reversing sale for ${item.itemCode}: removing ${item.quantity} from outBalance`);
              
              await updateInventoryItem(inventoryItem.id, {
                outBalance: newOutBalance,
                availableQuantity: newAvailableQuantity,
                totalBalance: newTotalBalance
              });
            }
          }
        }
        // Case 2: Status changed from draft to issued - APPLY all inventory
        else if (oldStatus === 'draft' && newStatus === 'issued') {
          console.log('Applying inventory changes (draft/cancelled → issued/paid)');
          
          for (const item of invoiceItems) {
            const inventoryItem = inventoryItems.find(
              inv => inv.itemCode.toUpperCase() === item.itemCode.toUpperCase()
            );
            
            if (inventoryItem) {
              const currentInBalance = Number(inventoryItem.inBalance || 0);
              const currentOutBalance = Number(inventoryItem.outBalance || 0);
              
              // Add NEW quantity to outBalance
              const newOutBalance = currentOutBalance + item.quantity;
              const newAvailableQuantity = currentInBalance - newOutBalance;
              const newTotalBalance = newAvailableQuantity;
              
              console.log(`  Applying sale for ${item.itemCode}: adding ${item.quantity} to outBalance`);
              
              await updateInventoryItem(inventoryItem.id, {
                outBalance: newOutBalance,
                availableQuantity: newAvailableQuantity,
                totalBalance: newTotalBalance
              });
            }
          }
        }
        // Case 3: Status remains issued - UPDATE quantity differences
        else if (oldStatus === 'issued' && newStatus === 'issued') {
          console.log('Updating inventory for quantity changes (issued/paid → issued/paid)');
          
          // Create a map of old items for easy lookup
          const oldItemsMap = new Map(editingInvoice.items.map(item => [item.itemCode.toUpperCase(), item.quantity]));
                    const newItemsMap = new Map(invoiceItems.map(item => [item.itemCode.toUpperCase(), item.quantity]));
          
          for (const newItem of invoiceItems) {
            const inventoryItem = inventoryItems.find(
              inv => inv.itemCode.toUpperCase() === newItem.itemCode.toUpperCase()
            );
            
            if (inventoryItem) {
              const oldQuantity = oldItemsMap.get(newItem.itemCode.toUpperCase()) || 0;
              const newQuantity = newItem.quantity;
              const quantityDifference = newQuantity - oldQuantity;
              
              if (quantityDifference !== 0) {
                const currentInBalance = Number(inventoryItem.inBalance || 0);
                const currentOutBalance = Number(inventoryItem.outBalance || 0);
                
                // Adjust outBalance by the difference
                const newOutBalance = Math.max(0, currentOutBalance + quantityDifference);
                const newAvailableQuantity = currentInBalance - newOutBalance;
                const newTotalBalance = newAvailableQuantity;
                
                console.log(`  Adjusting ${newItem.itemCode}: old qty ${oldQuantity} → new qty ${newQuantity} (diff: ${quantityDifference})`);
                console.log(`  Out Balance: ${currentOutBalance} → ${newOutBalance}`);

                          // Handle removed items (present in old invoice but removed from edited invoice)
                          for (const oldItem of editingInvoice.items) {
                            const oldCode = oldItem.itemCode.toUpperCase();
                            if (!newItemsMap.has(oldCode)) {
                              const inventoryItem = inventoryItems.find(
                                inv => inv.itemCode.toUpperCase() === oldCode
                              );

                              if (inventoryItem) {
                                const currentInBalance = Number(inventoryItem.inBalance || 0);
                                const currentOutBalance = Number(inventoryItem.outBalance || 0);

                                // Item removed from invoice, reverse its old sold quantity
                                const newOutBalance = Math.max(0, currentOutBalance - oldItem.quantity);
                                const newAvailableQuantity = currentInBalance - newOutBalance;
                                const newTotalBalance = newAvailableQuantity;

                                console.log(`  Removing item ${oldItem.itemCode}: reversing qty ${oldItem.quantity}`);
                                console.log(`  Out Balance: ${currentOutBalance} → ${newOutBalance}`);

                                await updateInventoryItem(inventoryItem.id, {
                                  outBalance: newOutBalance,
                                  availableQuantity: newAvailableQuantity,
                                  totalBalance: newTotalBalance
                                });
                              }
                            }
                          }
                
                await updateInventoryItem(inventoryItem.id, {
                  outBalance: newOutBalance,
                  availableQuantity: newAvailableQuantity,
                  totalBalance: newTotalBalance
                });
              }
            }
          }
        }
        
        // Update payment tracking and transactions when status changes to issued
        if (oldStatus === 'draft' && newStatus === 'issued') {
          const customer = customers.find(c => c.companyName === formData.customerName);
          if (customer && user) {
            try {
              // Create payment tracking transaction
              await createInvoiceTransaction(
                'customer',
                customer.id,
                customer.companyName,
                customer.customerCode,
                newInvoice.systemInvoiceNumber,
                totalAmount,
                formData.date,
                user.fullName
              );
              
              // Create transaction entry in basic accounting/transactions/expenses
              await addTransaction({
                id: '', // Will be generated by Firestore
                date: formData.date,
                description: `Invoice issued (on credit) ${newInvoice.systemInvoiceNumber} - ${formData.customerName}`,
                type: 'credit',
                amount: totalAmount,
                category: 'Product Sales',
                paymentMethod: 'On Credit',
                receiverName: formData.customerName,
                contraType: 'invoice',
                source: 'invoice'
              });
              
              console.log('✓ Created transaction entry for invoice status change to issued');
            } catch (error) {
              console.error('Error creating payment tracking transaction:', error);
              // Don't fail the invoice update if payment tracking fails
            }
          }
        }
        // Delete transaction when status changes from issued to draft
        else if (oldStatus === 'issued' && newStatus === 'draft') {
          try {
            // Delete transaction entries related to this invoice
            const transactionsRef = collection(db, 'transactions');
            const allTransactionsSnapshot = await getDocs(transactionsRef);
            
            for (const docSnap of allTransactionsSnapshot.docs) {
              const data = docSnap.data();
              // Check if transaction is related to this invoice
              if ((data.source === 'invoice' && data.description && data.description.includes(editingInvoice.systemInvoiceNumber)) ||
                  (data.contraType === 'invoice' && data.description && data.description.includes(editingInvoice.systemInvoiceNumber))) {
                await deleteDoc(docSnap.ref);
                console.log('✓ Deleted transaction entry for invoice status change to draft');
              }
            }
            
            // Delete payment tracking
            await deletePaymentTrackingByReference(editingInvoice.systemInvoiceNumber);
          } catch (error) {
            console.error('Error deleting transaction:', error);
          }
        }
        // Update payment tracking and accounting if amount changed (and status is issued)
        else if (oldStatus === 'issued' && newStatus === 'issued' && oldAmount !== newAmount) {
          console.log(`Invoice amount changed: ${oldAmount} → ${newAmount}`);

          try {
            // Update payment tracking amount
            await updateInvoicePaymentTrackingAmount(
              editingInvoice.systemInvoiceNumber,
              newAmount
            );
            console.log('✓ Updated payment tracking amount');

            // Update accounting transaction amount
            await updateAccountingTransactionForInvoice(
              editingInvoice.systemInvoiceNumber,
              newAmount
            );
            console.log('✓ Updated accounting transaction amount');
          } catch (error) {
            console.error('Error updating amounts:', error);
            // Don't fail the invoice update if amount update fails
          }
        }
      } else {
        // Add new invoice to Firebase
        await addInvoice(newInvoice);
        
        // REMOVED: Auto credit note generation to prevent duplicate sales entries in inventory
        // The invoice itself already updates inventory, no need for additional credit note
        
        // Create payment tracking transaction for issued status
        if (formData.status === 'issued') {
          const customer = customers.find(c => c.companyName === formData.customerName);
          if (customer && user) {
            try {
              await createInvoiceTransaction(
                'customer',
                customer.id,
                customer.companyName,
                customer.customerCode,
                newInvoice.systemInvoiceNumber,
                totalAmount,
                formData.date,
                user.fullName
              );
            } catch (error) {
              console.error('Error creating payment tracking transaction:', error);
            }
          }
        }
        
        // Create transaction entry when invoice is issued
        if (formData.status === 'issued') {
          await addTransaction({
            id: '', // Will be generated by Firestore
            date: formData.date,
            description: `Invoice issued (on credit) ${newInvoice.systemInvoiceNumber} - ${formData.customerName}`,
            type: 'credit',
            amount: totalAmount,
            category: 'Product Sales',
            paymentMethod: 'On Credit',
            receiverName: formData.customerName,
            contraType: 'invoice',
            source: 'invoice'
          });
        }
        
        // Update inventory ONLY if status is issued (not draft)
        if (formData.status === 'issued') {
          console.log(`=== Creating New Invoice with status: ${formData.status} ===`);
          console.log('Applying inventory changes...');
          
          for (const item of invoiceItems) {
            const inventoryItem = inventoryItems.find(
              inv => inv.itemCode.toUpperCase() === item.itemCode.toUpperCase()
            );
            
            if (inventoryItem) {
              const currentInBalance = Number(inventoryItem.inBalance || 0);
              const currentOutBalance = Number(inventoryItem.outBalance || 0);
              
              // Add sold quantity to outBalance
              const newOutBalance = currentOutBalance + item.quantity;
              const newAvailableQuantity = currentInBalance - newOutBalance;
              const newTotalBalance = newAvailableQuantity;
              
              console.log(`  Sale: Adding ${item.quantity} to outBalance for ${item.itemCode}`);
              console.log(`  Current Out Balance: ${currentOutBalance} → NEW Out Balance: ${newOutBalance}`);
              console.log(`  NEW Available Quantity: ${newAvailableQuantity}`);
              
              await updateInventoryItem(inventoryItem.id, {
                outBalance: newOutBalance,
                availableQuantity: newAvailableQuantity,
                totalBalance: newTotalBalance
              });
            } else {
              console.warn(`Inventory item not found for code: ${item.itemCode}`);
            }
          }
        } else {
          console.log(`Invoice created with status '${formData.status}' - no inventory update needed`);
        }
      }

      alert(editingInvoice ? 'Invoice updated successfully!' : 'Invoice created successfully!');
      resetForm();
    } catch (error) {
      console.error('Error saving invoice:', error);
      alert('Failed to save invoice. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  // Reset form
  const resetForm = () => {
    setFormData({
      date: new Date().toISOString().split('T')[0],
      customerName: '',
      customerPRN: '',
      manualInvoiceNumber: '',
      invoiceFrom: {
        pin: companyDetails.companyPIN,
        name: companyDetails.companyName,
        address: companyDetails.address,
        mobile: companyDetails.mobile,
      },
      items: [
        {
          itemCode: '',
          itemDescription: '',
          quantity: 1,
          unitPrice: 0,
          taxRate: 16,
        },
      ],
      status: 'draft',
    });
    setEditingInvoice(null);
    setShowAddForm(false);
  };

  // Handle edit
  const handleEdit = (invoice: Invoice) => {
    console.log('Edit button clicked for invoice:', invoice.systemInvoiceNumber);
    console.log('Current showAddForm state:', showAddForm);
    
    setEditingInvoice(invoice);
    const newFormData = {
      date: invoice.date,
      customerName: invoice.customerName,
      customerPRN: invoice.customerPRN,
      manualInvoiceNumber: invoice.manualInvoiceNumber,
      invoiceFrom: invoice.invoiceFrom || {
        pin: companyDetails.companyPIN,
        name: companyDetails.companyName,
        address: companyDetails.address,
        mobile: companyDetails.mobile,
      },
      items: invoice.items.map((item) => ({
        itemCode: item.itemCode,
        itemDescription: item.itemDescription,
        quantity: item.quantity,
        unitPrice: item.unitPrice,
        taxRate: item.taxRate,
      })),
      status: invoice.status,
    };
    
    console.log('Setting form data:', newFormData);
    setFormData(newFormData);
    
    console.log('Setting showAddForm to true');
    setShowAddForm(true);
    
    // Scroll to form after state updates
    setTimeout(() => {
      console.log('Scrolling to top');
      const mainContent = document.querySelector('.min-h-screen') || document.body;
      mainContent.scrollTo({ top: 0, behavior: 'smooth' });
      window.scrollTo({ top: 0, behavior: 'smooth' });
      
      // Also try to scroll the form into view
      const formElement = document.querySelector('form');
      if (formElement) {
        formElement.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
      console.log('Form element found:', !!formElement);
    }, 100);
  };

  // Handle delete
  const handleDelete = async (id: string) => {
    if (confirm('Are you sure you want to delete this invoice? This will also reverse the inventory changes if applicable.')) {
      try {
        // Find the invoice to get its details before deletion
        const invoiceToDelete = invoices.find(inv => inv.id === id);
        
        if (!invoiceToDelete) {
          alert('Invoice not found');
          return;
        }

        console.log('=== Deleting invoice ===');
        console.log(`Invoice ID: ${id}`);
        console.log(`Status: ${invoiceToDelete.status}`);

        // Only reverse inventory if the invoice was issued
        if (invoiceToDelete.status === 'issued') {
          console.log('Invoice was issued - reversing inventory changes...');
          
          // Fetch latest inventory data
          for (const item of invoiceToDelete.items) {
            const inventoryItem = inventoryItems.find(
              inv => inv.itemCode.toUpperCase() === item.itemCode.toUpperCase()
            );
            
            if (inventoryItem) {
              const currentInBalance = Number(inventoryItem.inBalance || 0);
              const currentOutBalance = Number(inventoryItem.outBalance || 0);
              
              // Remove the quantity from outBalance (reverse the sale)
              const newOutBalance = Math.max(0, currentOutBalance - item.quantity);
              const newAvailableQuantity = currentInBalance - newOutBalance;
              const newTotalBalance = newAvailableQuantity;
              
              console.log(`  Reversing sale for ${item.itemCode}: removing ${item.quantity} from outBalance`);
              console.log(`  Current Out Balance: ${currentOutBalance} → NEW Out Balance: ${newOutBalance}`);
              
              await updateInventoryItem(inventoryItem.id, {
                outBalance: newOutBalance,
                availableQuantity: newAvailableQuantity,
                totalBalance: newTotalBalance
              });
            } else {
              console.warn(`Inventory item not found for code: ${item.itemCode}`);
            }
          }
        } else {
          console.log(`Invoice status was '${invoiceToDelete.status}' - no inventory reversal needed`);
        }

        // Delete payment tracking records associated with this invoice
        await deletePaymentTrackingByReference(invoiceToDelete.systemInvoiceNumber);

        // Delete income/expense transaction (regardless of status)
        try {
          // Query and delete transaction from income/expense
          const transactionsQuery = query(
            collection(db, 'transactions'),
            where('source', '==', 'invoice')
          );
          const transactionsSnapshot = await getDocs(transactionsQuery);
          
          for (const docSnap of transactionsSnapshot.docs) {
            const data = docSnap.data();
            // Check if this transaction is related to this invoice by checking description
            if (data.description && data.description.includes(invoiceToDelete.systemInvoiceNumber)) {
              await deleteDoc(docSnap.ref);
              console.log('✓ Deleted associated income transaction');
            }
          }
        } catch (error) {
          console.error('Error deleting income transaction:', error);
        }

        // Delete the invoice from Firestore
        await deleteInvoice(id);
        console.log('✓✓✓ Invoice deleted successfully');
        alert('Invoice deleted successfully!');
      } catch (error) {
        console.error('Error deleting invoice:', error);
        alert('Failed to delete invoice. Please try again.');
      }
    }
  };

  // Print invoice in Donato Impex Ltd. format
  const handlePrint = (invoice: Invoice) => {
    // Create hidden iframe for printing in same tab
    const iframe = document.createElement('iframe');
    iframe.style.position = 'fixed';
    iframe.style.right = '0';
    iframe.style.bottom = '0';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.style.border = 'none';
    document.body.appendChild(iframe);

    const iframeDoc = iframe.contentWindow?.document;
    if (!iframeDoc) return;

    // Get customer details
    const customer = customers.find(c => c.companyName === invoice.customerName);

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Invoice - ${invoice.systemInvoiceNumber}</title>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <style>
            @page {
              margin: 1.5cm 1cm 1.5cm 1cm;
              size: A4;
              padding: 0;
            }
            @media print {
              * {
                -webkit-print-color-adjust: exact !important;
                print-color-adjust: exact !important;
              }
              html {
                margin: 0;
                padding: 0;
              }
              body {
                margin: 0;
                padding: 10px;
                background: white;
              }
            }
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body {
              font-family: Arial, sans-serif;
              padding: 20px;
              font-size: 11px;
              color: #000;
              background: #fff;
              display: flex;
              flex-direction: column;
              min-height: 277mm;
              max-height: 277mm;
            }
            .content-wrapper {
              flex: 1;
              display: flex;
              flex-direction: column;
            }
            .main-content {
              flex: 0 0 auto;
            }
            .spacer {
              flex: 1;
            }
            .bottom-section {
              flex: 0 0 auto;
              margin-top: auto;
            }
            .header {
              text-align: center;
              margin-bottom: 20px;
              border-bottom: 3px solid #000;
              padding-bottom: 10px;
            }
            .logo {
              font-size: 22px;
              font-weight: bold;
              margin-bottom: 5px;
            }
            .invoice-info {
              display: flex;
              justify-content: space-between;
              margin-bottom: 15px;
              border: 2px solid #000;
            }
            .info-box {
              flex: 1;
              padding: 10px;
              border-right: 1px solid #000;
            }
            .info-box:last-child {
              border-right: none;
            }
            .info-box h3 {
              font-size: 11px;
              margin-bottom: 6px;
              font-weight: bold;
              text-decoration: underline;
            }
            .info-box p {
              font-size: 10px;
              margin: 3px 0;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin: 15px 0;
              border: 2px solid #000;
            }
            th, td {
              border: 1px solid #000;
              padding: 8px 5px;
              text-align: left;
              font-size: 10px;
            }
            th {
              background-color: #000;
              color: #fff;
              font-weight: bold;
              text-align: center;
            }
            tbody tr:nth-child(even) {
              background-color: #f5f5f5;
            }
            .text-center { text-align: center; }
            .text-right { text-align: right; }
            .tax-summary-section {
              width: 100%;
              border: 2px solid #000;
              padding: 10px;
              margin-bottom: 10px;
            }
            .tax-summary table {
              width: 100%;
              border: 1px solid #000;
            }
            .tax-summary th {
              background-color: #000;
              color: #fff;
              text-align: center;
              padding: 6px;
              font-weight: bold;
            }
            .tax-summary td {
              text-align: right;
              padding: 6px;
              border: 1px solid #000;
            }
            .total-row {
              font-weight: bold;
              border-top: 2px solid #000;
            }
            .footer {
              padding-top: 10px;
              border-top: 1px solid #000;
              text-align: center;
              font-size: 9px;
            }
            .footer p { margin: 3px 0; }
          </style>
        </head>
        <body>
          <div class="main-content">
            <div class="header">
              <div class="logo">
                ${invoice.invoiceFrom?.name || 'DONATO IMPEX LIMITED'}
              </div>
            </div>

            <div class="invoice-info">
              <div class="info-box">
                <h3>INVOICE FROM</h3>
                <p><strong>NAME:</strong> ${invoice.invoiceFrom?.name || 'DONATO IMPEX LIMITED'}</p>
                <p><strong>PIN:</strong> ${invoice.invoiceFrom?.pin || 'P052210668Q'}</p>
                <p><strong>ADDRESS:</strong> ${invoice.invoiceFrom?.address || 'P.O. BOX 12345, NAIROBI'}</p>
                <p><strong>MOBILE:</strong> ${invoice.invoiceFrom?.mobile || '+254 700 000 000'}</p>
              </div>
              <div class="info-box">
                <h3>INVOICE TO</h3>
                <p><strong>NAME:</strong> ${invoice.customerName.toUpperCase()}</p>
                <p><strong>Customer PIN:</strong> ${invoice.customerPRN || 'N/A'}</p>
                <p><strong>ADDRESS:</strong> ${customer?.address || 'N/A'}</p>
                <p><strong>MOBILE:</strong> ${customer?.contactNumber || 'N/A'}</p>
              </div>
              <div class="info-box">
                <h3>INVOICE NO.</h3>
                <p><strong>Invoice:</strong> ${invoice.systemInvoiceNumber}</p>
                <p><strong>CU Number:</strong> ${invoice.manualInvoiceNumber}</p>
                <p><strong>Date:</strong> ${new Date(invoice.date).toLocaleDateString('en-GB')} ${new Date(invoice.date).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit' })}</p>
              </div>
            </div>

            <table>
              <thead>
                <tr>
                  <th style="width: 40px;">S/N</th>
                  <th>Item Description</th>
                  <th style="width: 80px;">Qty</th>
                  <th style="width: 100px;">Unit Price</th>
                  <th style="width: 60px;">Rate</th>
                  <th style="width: 120px;">Amt incl. Tax</th>
                </tr>
              </thead>
              <tbody>
                ${invoice.items
                  .map(
                    (item, index) => `
                  <tr>
                    <td class="text-center">${index + 1}</td>
                    <td>${item.itemDescription.toUpperCase()}</td>
                    <td class="text-center">${formatKenyanNumber(item.quantity)}</td>
                    <td class="text-right">KSh ${formatKenyanNumber(item.unitPrice)}</td>
                    <td class="text-center">${item.taxRate}%</td>
                    <td class="text-right">KSh ${formatKenyanNumber(item.amountInclTax)}</td>
                  </tr>
                `
                  )
                  .join('')}
              </tbody>
            </table>
          </div>

          <div class="spacer"></div>

          <div class="bottom-section">
            <div class="tax-summary-section">
              <p style="font-weight: bold; margin-bottom: 10px;">TAX SUMMARY</p>
              <table class="tax-summary">
                <tr>
                  <th>Tax Rate</th>
                  <th>Taxable Amt</th>
                  <th>Tax Amt</th>
                  <th>Total Amt</th>
                </tr>
                <tr>
                  <td class="text-center">16%</td>
                  <td class="text-right">KSh ${formatKenyanNumber(invoice.taxableTotalAmount)}</td>
                  <td class="text-right">KSh ${formatKenyanNumber(invoice.totalTaxAmount)}</td>
                  <td class="text-right">KSh ${formatKenyanNumber(invoice.totalAmount)}</td>
                </tr>
                <tr>
                  <td class="text-center">0%</td>
                  <td class="text-right">KSh 0.00</td>
                  <td class="text-right">KSh 0.00</td>
                  <td class="text-right">KSh 0.00</td>
                </tr>
                <tr>
                  <td class="text-center">Ex.</td>
                  <td class="text-right">KSh 0.00</td>
                  <td class="text-right">KSh 0.00</td>
                  <td class="text-right">KSh 0.00</td>
                </tr>
                <tr class="total-row">
                  <td class="text-center"><strong>Totals</strong></td>
                  <td class="text-right"><strong>KSh ${formatKenyanNumber(invoice.taxableTotalAmount)}</strong></td>
                  <td class="text-right"><strong>KSh ${formatKenyanNumber(invoice.totalTaxAmount)}</strong></td>
                  <td class="text-right"><strong>KSh ${formatKenyanNumber(invoice.totalAmount)}</strong></td>
                </tr>
              </table>
            </div>

            <div class="footer">
              <p>This invoice was generated on ${new Date().toLocaleDateString('en-GB')} at ${new Date().toLocaleTimeString('en-GB')}</p>
              <p>Recycle Business Manager - Invoice System</p>
            </div>
          </div>
          
          <script>
            window.onload = function() {
              window.print();
            };
          </script>
        </body>
      </html>
    `;

    iframeDoc.open();
    iframeDoc.write(htmlContent);
    iframeDoc.close();

    // Clean up after printing
    iframe.contentWindow?.addEventListener('afterprint', () => {
      setTimeout(() => {
        document.body.removeChild(iframe);
      }, 100);
    });
  };

  // Download CSV
  const handleDownload = () => {
    const csvContent = [
      [
        'System Invoice No',
        'CU Number',
        'Date',
        'Customer',
        'PIN',
        'Items Count',
        'Taxable Amount',
        'Tax Amount',
        'Total Amount',
        'Status',
      ].join(','),
      ...filteredInvoices.map((inv) =>
        [
          inv.systemInvoiceNumber,
          inv.manualInvoiceNumber,
          inv.date,
          `"${inv.customerName}"`,
          inv.customerPRN,
          inv.items.length,
          formatKenyanNumber(inv.taxableTotalAmount, 2),
          formatKenyanNumber(inv.totalTaxAmount, 2),
          formatKenyanNumber(inv.totalAmount, 2),
          inv.status.toUpperCase(),
        ].join(',')
      ),
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `invoices_${new Date().toISOString().split('T')[0]}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Download PDF with print preview
  const handleDownloadPDF = () => {
    const doc = new jsPDF('l', 'mm', 'a4');
    
    // Professional B&W Header with Company Name (from companyDetails)
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(companyDetails.companyName.toUpperCase(), 148, 12, { align: 'center' });
    
    doc.setFontSize(18);
    doc.text('RECYCLE BUSINESS MANAGER', 148, 20, { align: 'center' });
    
    doc.setFontSize(14);
    doc.text('Invoices Report', 148, 28, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on ${new Date().toLocaleDateString('en-GB')}`, 148, 34, { align: 'center' });
    
    // Divider line
    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.5);
    doc.line(15, 38, 281, 38);

    // Summary boxes - B&W with borders
    const summaryY = 45;
    const startX = 15;
    
    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.3);
    doc.rect(startX, summaryY, 65, 20, 'S');
    doc.rect(startX + 70, summaryY, 65, 20, 'S');
    doc.rect(startX + 140, summaryY, 65, 20, 'S');
    doc.rect(startX + 210, summaryY, 65, 20, 'S');
    
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL INVOICES', startX + 5, summaryY + 8);
    doc.text('TOTAL AMOUNT', startX + 75, summaryY + 8);
    doc.text('TAXABLE AMOUNT', startX + 145, summaryY + 8);
    doc.text('TAX AMOUNT', startX + 215, summaryY + 8);
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    const totalAmount = filteredInvoices.reduce((sum, inv) => sum + inv.totalAmount, 0);
    const taxableAmount = filteredInvoices.reduce((sum, inv) => sum + inv.taxableTotalAmount, 0);
    const taxAmount = filteredInvoices.reduce((sum, inv) => sum + inv.totalTaxAmount, 0);
    doc.text(`${filteredInvoices.length}`, startX + 5, summaryY + 16);
    doc.text(`KSH ${formatKenyanNumber(totalAmount)}`, startX + 75, summaryY + 16);
    doc.text(`KSH ${formatKenyanNumber(taxableAmount)}`, startX + 145, summaryY + 16);
    doc.text(`KSH ${formatKenyanNumber(taxAmount)}`, startX + 215, summaryY + 16);

    // Table data with Kenyan formatting
    const tableData = filteredInvoices.map(inv => ([
      inv.systemInvoiceNumber,
      inv.manualInvoiceNumber,
      inv.date,
      inv.customerName,
      inv.customerPRN,
      inv.items.length.toString(),
      formatKenyanNumber(inv.taxableTotalAmount),
      formatKenyanNumber(inv.totalTaxAmount),
      formatKenyanNumber(inv.totalAmount),
      inv.status.toUpperCase()
    ]));

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    autoTable(doc, {
      startY: summaryY + 25,
      head: [['System Invoice', 'CU Number', 'Date', 'Customer', 'PIN', 'Items', 'Taxable (KSH)', 'Tax (KSH)', 'Total (KSH)', 'Status']],
      body: tableData,
      theme: 'plain',
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      headStyles: {
        fillColor: [255, 255, 255],
        textColor: [0, 0, 0],
        fontSize: 8,
        fontStyle: 'bold',
        lineWidth: 0.3,
        lineColor: [0, 0, 0]
      } as any,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      bodyStyles: {
        fontSize: 8,
        textColor: [0, 0, 0],
        lineWidth: 0.1,
        lineColor: [0, 0, 0]
      } as any,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      alternateRowStyles: {
        fillColor: [255, 255, 255]
      } as any,
      margin: { left: 15, right: 15 }
    });
    
    // Footer
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const finalY = (doc as any).lastAutoTable.finalY || summaryY + 30;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text('This is a computer-generated document. No signature required.', 148, finalY + 10, { align: 'center' });
    doc.text('Recycle Business Manager - Invoice Management System', 148, finalY + 15, { align: 'center' });

    // Open native print dialog first
    const pdfBlob = doc.output('blob');
    const pdfUrl = URL.createObjectURL(pdfBlob);
    const iframe = document.createElement('iframe');
    iframe.style.display = 'none';
    iframe.src = pdfUrl;
    document.body.appendChild(iframe);
    iframe.onload = () => {
      setTimeout(() => {
        iframe.contentWindow?.print();
        
        // Listen for after print event to download
        iframe.contentWindow?.addEventListener('afterprint', () => {
          doc.save('invoices_report.pdf');
          // Clean up
          setTimeout(() => {
            document.body.removeChild(iframe);
            URL.revokeObjectURL(pdfUrl);
          }, 100);
        });
        
        // Also clean up if user cancels (after 30 seconds timeout)
        setTimeout(() => {
          if (document.body.contains(iframe)) {
            document.body.removeChild(iframe);
            URL.revokeObjectURL(pdfUrl);
          }
        }, 30000);
      }, 100);
    };
  };

  // Filter invoices
  const filteredInvoices = invoices.filter((inv) => {
    const matchesSearch =
      searchTerm === '' ||
      inv.systemInvoiceNumber.toLowerCase().includes(searchTerm.toLowerCase()) ||
      inv.manualInvoiceNumber.toLowerCase().includes(searchTerm.toLowerCase()) ||
      inv.customerName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      inv.customerPRN.toLowerCase().includes(searchTerm.toLowerCase());

    const matchesStatus = filterStatus === 'all' || inv.status === filterStatus;

    return matchesSearch && matchesStatus;
  }).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()); // Sort by date descending

  const { taxableTotalAmount, totalTaxAmount, totalAmount } = calculateInvoiceTotals();

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 flex items-center gap-3">
            <div className="p-3 bg-emerald-50 rounded-xl">
              <FileSpreadsheet className="w-8 h-8 text-emerald-600" />
            </div>
            Invoice Management
          </h1>
          <p className="text-gray-600 mt-2">Generate and manage Donato Impex Ltd. compliant invoices</p>
        </div>
        <button
          onClick={() => setShowAddForm(!showAddForm)}
          className="px-4 py-2.5 bg-emerald-600 text-white rounded-lg font-semibold flex items-center gap-2 hover:bg-emerald-700 transition-colors"
        >
          <Plus className="w-5 h-5" />
          Create Invoice
        </button>
      </div>

      {/* Add/Edit Form */}
      {showAddForm && (
        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <h3 className="text-lg font-bold text-gray-900 mb-4">
            {editingInvoice ? 'Edit Invoice' : 'Create New Invoice'}
          </h3>
          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Basic Info */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Date</label>
                <input
                  type="date"
                  value={formData.date}
                  onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                  className="w-full px-4 py-2.5 rounded-lg border border-gray-300 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Customer</label>
                <select
                  value={formData.customerName}
                  onChange={(e) => {
                    const customerName = e.target.value;
                    setFormData({
                      ...formData,
                      customerName,
                      customerPRN: getCustomerPRN(customerName),
                    });
                  }}
                  className="w-full px-4 py-2.5 rounded-lg border border-gray-300 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none"
                  required
                >
                  <option value="">Select Customer</option>
                  {customers.map((customer) => (
                    <option key={customer.id} value={customer.companyName}>
                      {customer.companyName} ({customer.customerCode})
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Customer PIN</label>
                <input
                  type="text"
                  value={formData.customerPRN}
                  onChange={(e) => setFormData({ ...formData, customerPRN: e.target.value })}
                  placeholder="P051410641HC"
                  className="w-full px-4 py-2.5 rounded-lg border border-gray-300 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none"
                  required
                />
              </div>
            </div>

            {/* Invoice Numbers */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  System Invoice Number
                </label>
                <input
                  type="text"
                  value={editingInvoice?.systemInvoiceNumber || 'Will be auto-generated'}
                  disabled
                  className="w-full px-4 py-2.5 rounded-lg border border-gray-300 bg-gray-100 text-gray-600 cursor-not-allowed"
                />
                <p className="text-xs text-gray-500 mt-1">Auto-generated sequentially</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  CU Number
                </label>
                <input
                  type="text"
                  value={formData.manualInvoiceNumber}
                  onChange={(e) => setFormData({ ...formData, manualInvoiceNumber: e.target.value })}
                  placeholder="Enter invoice number manually"
                  className="w-full px-4 py-2.5 rounded-lg border border-gray-300 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none"
                  required
                />
                <p className="text-xs text-gray-500 mt-1">Enter your custom invoice number</p>
              </div>
            </div>

            {/* Items Section */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="block text-sm font-medium text-gray-700">Invoice Items</label>
                <button
                  type="button"
                  onClick={addItemRow}
                  className="text-emerald-600 hover:text-emerald-700 flex items-center gap-1 text-sm font-medium"
                >
                  <Plus className="w-4 h-4" />
                  Add Item
                </button>
              </div>
              <div className="relative">
                <div style={{ overflowX: 'auto' }}>
                  <table className="w-full border border-gray-300 rounded-lg relative">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-3 py-2 text-left text-xs font-semibold text-gray-600">
                        Item Code
                      </th>
                      <th className="px-3 py-2 text-left text-xs font-semibold text-gray-600">
                        Description
                      </th>
                      <th className="px-3 py-2 text-left text-xs font-semibold text-gray-600">
                        Available
                      </th>
                      <th className="px-3 py-2 text-left text-xs font-semibold text-gray-600">
                        Quantity
                      </th>
                      <th className="px-3 py-2 text-left text-xs font-semibold text-gray-600">
                        Unit Price
                      </th>
                      <th className="px-3 py-2 text-left text-xs font-semibold text-gray-600">
                        Tax Rate (%)
                      </th>
                      <th className="px-3 py-2 text-right text-xs font-semibold text-gray-600">
                        Excl. Tax
                      </th>
                      <th className="px-3 py-2 text-right text-xs font-semibold text-gray-600">
                        Tax
                      </th>
                      <th className="px-3 py-2 text-right text-xs font-semibold text-gray-600">
                        Incl. Tax
                      </th>
                      <th className="px-3 py-2"></th>
                    </tr>
                  </thead>
                  <tbody>
                    {formData.items.map((item, index) => {
                      const { amountExclTax, taxAmount, amountInclTax } = calculateItemTotals(
                        item.quantity,
                        item.unitPrice,
                        item.taxRate
                      );
                      const inventoryItem = inventoryItems.find(
                        inv => inv.itemCode.toUpperCase() === item.itemCode.toUpperCase().trim()
                      );
                      return (
                        <tr key={index} className="border-t border-gray-200">
                          <td className="px-3 py-2" style={{position: 'relative', zIndex: 20}}>
                            <div className="relative">
                              <input
                                type="text"
                                value={item.itemCode}
                                onChange={(e) => handleItemChange(index, 'itemCode', e.target.value)}
                                onFocus={() => {
                                  if (item.itemCode.trim()) {
                                    setShowItemCodeDropdowns({ ...showItemCodeDropdowns, [index]: true });
                                  }
                                }}
                                onBlur={() => {
                                  setTimeout(() => {
                                    setShowItemCodeDropdowns({ ...showItemCodeDropdowns, [index]: false });
                                  }, 200);
                                }}
                                placeholder="CODE001"
                                className="w-full px-2 py-1 rounded border border-gray-300 focus:ring-emerald-500 focus:border-emerald-500 focus:ring-2 outline-none text-sm"
                                required
                              />
                              {/* Item Code Suggestions Dropdown */}
                              {showItemCodeDropdowns[index] && getFilteredItemCodes(index).length > 0 && (
                                <div className="absolute top-full left-0 z-50 bg-white border border-gray-300 rounded-lg shadow-2xl max-h-48 overflow-y-auto min-w-[250px] mt-1">
                                  {getFilteredItemCodes(index).map((invItem) => (
                                    <div
                                      key={invItem.id}
                                      onClick={() => handleSelectItemCode(index, invItem)}
                                      className="px-3 py-2 hover:bg-blue-50 cursor-pointer border-b border-gray-100 last:border-b-0"
                                    >
                                      <div className="font-semibold text-sm text-gray-900">{invItem.itemCode}</div>
                                      <div className="text-xs text-gray-600">{invItem.itemName}</div>
                                    </div>
                                  ))}
                                </div>
                              )}
                            </div>
                          </td>
                          <td className="px-3 py-2">
                            <div className="relative">
                              <input
                                type="text"
                                value={item.itemDescription}
                                onChange={(e) =>
                                  handleItemChange(index, 'itemDescription', e.target.value)
                                }
                                placeholder="Item description"
                                className={`w-full px-2 py-1 rounded border border-gray-300 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none text-sm ${
                                  item.itemCode && inventoryItems.find(inv => inv.itemCode.toUpperCase() === item.itemCode.toUpperCase())
                                    ? 'bg-green-50'
                                    : ''
                                }`}
                                title={
                                  item.itemCode && inventoryItems.find(inv => inv.itemCode.toUpperCase() === item.itemCode.toUpperCase())
                                    ? 'Auto-filled from inventory'
                                    : ''
                                }
                                required
                              />
                            </div>
                          </td>
                          <td className="px-3 py-2">
                            {inventoryItem ? (
                              <div className="flex items-center gap-1">
                                <span className={`text-sm font-semibold ${
                                  inventoryItem.availableQuantity > 0 ? 'text-green-600' : 'text-red-600'
                                }`}>
                                  {formatKenyanNumber(inventoryItem.availableQuantity)}
                                </span>
                                <span className="text-xs text-gray-500">{inventoryItem.unit}</span>
                              </div>
                            ) : (
                              <span className="text-xs text-gray-400">-</span>
                            )}
                          </td>
                          <td className="px-3 py-2">
                            <input
                              type="number"
                              value={item.quantity}
                              onChange={(e) =>
                                handleItemChange(index, 'quantity', parseFloat(e.target.value) || 0)
                              }
                              min="0"
                              step="0.0001"
                              className="w-20 px-2 py-1 rounded border border-gray-300 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none text-sm"
                              required
                            />
                          </td>
                          <td className="px-3 py-2">
                            <input
                              type="number"
                              value={item.unitPrice}
                              onChange={(e) =>
                                handleItemChange(index, 'unitPrice', parseFloat(e.target.value) || 0)
                              }
                              min="0"
                              step="0.01"
                              className="w-24 px-2 py-1 rounded border border-gray-300 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none text-sm"
                              required
                            />
                          </td>
                          <td className="px-3 py-2">
                            <select
                              value={item.taxRate}
                              onChange={(e) =>
                                handleItemChange(index, 'taxRate', parseFloat(e.target.value))
                              }
                              className="w-16 px-2 py-1 rounded border border-gray-300 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none text-sm"
                              required
                            >
                              <option value="0">0</option>
                              <option value="16">16</option>
                            </select>
                          </td>
                          <td className="px-3 py-2 text-right text-sm font-medium">
                            {formatKenyanNumber(amountExclTax)}
                          </td>
                          <td className="px-3 py-2 text-right text-sm font-medium">
                            {formatKenyanNumber(taxAmount)}
                          </td>
                          <td className="px-3 py-2 text-right text-sm font-medium">
                            {formatKenyanNumber(amountInclTax)}
                          </td>
                          <td className="px-3 py-2">
                            {formData.items.length > 1 && (
                              <button
                                type="button"
                                onClick={() => removeItemRow(index)}
                                className="p-1 text-red-600 hover:bg-red-50 rounded transition-colors"
                              >
                                <Trash2 className="w-4 h-4" />
                              </button>
                            )}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
              </div>
            </div>

            {/* Totals Display */}
            <div className="bg-gray-50 rounded-lg p-4">
              <div className="grid grid-cols-3 gap-4 text-sm">
                <div>
                  <span className="text-gray-600">Taxable Amount:</span>
                  <p className="font-bold text-lg">KSh {formatKenyanNumber(taxableTotalAmount)}</p>
                </div>
                <div>
                  <span className="text-gray-600">Tax Amount:</span>
                  <p className="font-bold text-lg">KSh {formatKenyanNumber(totalTaxAmount)}</p>
                </div>
                <div>
                  <span className="text-gray-600">Total Amount:</span>
                  <p className="font-bold text-lg text-emerald-600">KSh {formatKenyanNumber(totalAmount)}</p>
                </div>
              </div>
            </div>

            {/* Status */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Status</label>
                <select
                  value={formData.status}
                  onChange={(e) =>
                    setFormData({
                      ...formData,
                      status: e.target.value as 'draft' | 'issued',
                    })
                  }
                  className="w-full px-4 py-2.5 rounded-lg border border-gray-300 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none"
                  required
                >
                  <option value="draft">Draft</option>
                  <option value="issued">Issued</option>
                </select>
              </div>
            </div>

            {/* Form Actions */}
            <div className="flex gap-3">
              <button
                type="submit"
                disabled={saving}
                className="px-6 py-2.5 bg-emerald-600 text-white rounded-lg font-semibold hover:bg-emerald-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
              >
                {saving ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                    Saving...
                  </>
                ) : editingInvoice ? (
                  'Update Invoice'
                ) : (
                  'Create Invoice'
                )}
              </button>
              <button
                type="button"
                onClick={resetForm}
                disabled={saving}
                className="px-6 py-2.5 bg-gray-200 text-gray-700 rounded-lg font-semibold hover:bg-gray-300 transition-colors disabled:opacity-50"
              >
                Cancel
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Filters and Search */}
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="relative col-span-2">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              type="text"
              placeholder="Search invoices..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none"
            />
          </div>
          <select
            value={filterStatus}
            onChange={(e) => setFilterStatus(e.target.value as typeof filterStatus)}
            className="px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 outline-none"
          >
            <option value="all">All Status</option>
            <option value="draft">Draft</option>
            <option value="issued">Issued</option>
          </select>
        </div>
      </div>

      {/* Invoices List */}
      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
        <div className="p-6 border-b border-gray-200">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <FileSpreadsheet className="w-5 h-5 text-gray-600" />
              <h3 className="text-lg font-bold text-gray-900">Invoices</h3>
              <span className="text-sm text-gray-500">({filteredInvoices.length} invoices)</span>
            </div>
            <div className="flex items-center gap-3">
              <button
                onClick={handleDownload}
                className="px-4 py-2 bg-emerald-600 text-white rounded-lg font-semibold flex items-center gap-2 hover:bg-emerald-700 transition-colors"
              >
                <Download className="w-4 h-4" />
                Export CSV
              </button>
              <button
                onClick={handleDownloadPDF}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg font-semibold flex items-center gap-2 hover:bg-blue-700 transition-colors"
              >
                <Printer className="w-4 h-4" />
                Export PDF
              </button>
            </div>
          </div>
        </div>

        {filteredInvoices.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                    System Invoice
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                    CU Number
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                    Date
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                    Customer
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                    PIN
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                    Items
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-semibold text-gray-600 uppercase">
                    Total Amount
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                    Status
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-semibold text-gray-600 uppercase">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {filteredInvoices.map((invoice) => (
                  <tr key={invoice.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 text-sm font-medium text-gray-900">
                      {invoice.systemInvoiceNumber}
                    </td>
                    <td className="px-6 py-4 text-sm font-medium text-emerald-600">
                      {invoice.manualInvoiceNumber}
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-700">
                      {new Date(invoice.date).toLocaleDateString()}
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-900">{invoice.customerName}</td>
                    <td className="px-6 py-4 text-sm text-gray-700">{invoice.customerPRN}</td>
                    <td className="px-6 py-4 text-sm text-gray-700">{invoice.items.length}</td>
                    <td className="px-6 py-4 text-sm font-bold text-gray-900 text-right">
                      KSh {formatKenyanNumber(invoice.totalAmount)}
                    </td>
                    <td className="px-6 py-4 text-sm">
                      <span
                        className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                          invoice.status === 'issued'
                            ? 'bg-blue-100 text-blue-700'
                            : 'bg-yellow-100 text-yellow-700'
                        }`}
                      >
                        {invoice.status.toUpperCase()}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-right">
                      <div className="flex items-center justify-end gap-2">
                        <button
                          onClick={() => handlePrint(invoice)}
                          className="p-1.5 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                          title="Print"
                        >
                          <Printer className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleEdit(invoice)}
                          className="p-1.5 text-emerald-600 hover:bg-emerald-50 rounded-lg transition-colors"
                          title="Edit"
                        >
                          <Edit2 className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleDelete(invoice.id)}
                          className="p-1.5 text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                          title="Delete"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="p-12 text-center">
            <FileSpreadsheet className="w-16 h-16 text-gray-300 mx-auto mb-3" />
            <p className="text-gray-500">No invoices found</p>
            <p className="text-sm text-gray-400 mt-2">
              {searchTerm || filterStatus !== 'all'
                ? 'Try adjusting your search or filters'
                : 'Create your first invoice to get started'}
            </p>
          </div>
        )}
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-emerald-50 rounded-lg">
              <FileSpreadsheet className="w-5 h-5 text-emerald-600" />
            </div>
            <h3 className="text-sm font-semibold text-gray-600">Total Invoices</h3>
          </div>
          <p className="text-2xl font-bold text-gray-900">{invoices.length}</p>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-yellow-50 rounded-lg">
              <FileSpreadsheet className="w-5 h-5 text-yellow-600" />
            </div>
            <h3 className="text-sm font-semibold text-gray-600">Draft</h3>
          </div>
          <p className="text-2xl font-bold text-gray-900">
            {invoices.filter((i) => i.status === 'draft').length}
          </p>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-blue-50 rounded-lg">
              <FileSpreadsheet className="w-5 h-5 text-blue-600" />
            </div>
            <h3 className="text-sm font-semibold text-gray-600">Issued</h3>
          </div>
          <p className="text-2xl font-bold text-gray-900">
            {invoices.filter((i) => i.status === 'issued').length}
          </p>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-purple-50 rounded-lg">
              <FileSpreadsheet className="w-5 h-5 text-purple-600" />
            </div>
            <h3 className="text-sm font-semibold text-gray-600">Total Revenue</h3>
          </div>
          <p className="text-2xl font-bold text-gray-900">
            KSh {formatKenyanNumber(invoices.reduce((sum, inv) => sum + inv.totalAmount, 0))}
          </p>
        </div>
      </div>

      {/* Print Preview Modal */}
      {printPreviewInvoice && (() => {
        const customer = customers.find(c => c.companyName === printPreviewInvoice.customerName);
        return (
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[9999] p-4">
            <div className="bg-white rounded-2xl w-full max-w-4xl max-h-[90vh] overflow-hidden shadow-2xl">
              {/* Modal Header */}
              <div className="flex items-center justify-between p-6 border-b border-gray-200 bg-gradient-to-r from-emerald-50 to-blue-50">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-white rounded-lg shadow-sm">
                    <Eye className="w-6 h-6 text-emerald-600" />
                  </div>
                  <div>
                    <h2 className="text-xl font-bold text-gray-900">Print Preview</h2>
                    <p className="text-sm text-gray-600">Invoice: {printPreviewInvoice.systemInvoiceNumber}</p>
                  </div>
                </div>
                <button
                  onClick={() => setPrintPreviewInvoice(null)}
                  className="p-2 hover:bg-white/80 rounded-lg transition-colors"
                >
                  <X className="w-5 h-5 text-gray-600" />
                </button>
              </div>

              {/* Preview Content */}
              <div className="overflow-y-auto max-h-[calc(90vh-180px)] p-8 bg-gray-50">
                <div className="bg-white rounded-lg shadow-sm p-8" id="print-preview-content">
                  {/* Invoice Header */}
                  <div className="text-center mb-6 border-b-2 border-gray-800 pb-4">
                    <div className="text-2xl font-bold text-red-600 mb-2">
                      {printPreviewInvoice.invoiceFrom?.name || 'DONATO IMPEX LIMITED'}
                    </div>
                  </div>

                  {/* Invoice Information */}
                  <div className="grid grid-cols-3 gap-4 mb-6 border border-gray-800">
                    <div className="border-r border-gray-800 p-4">
                      <h3 className="text-xs font-bold mb-2">INVOICE FROM</h3>
                      <p className="text-xs"><strong>PIN:</strong> {printPreviewInvoice.invoiceFrom?.pin}</p>
                      <p className="text-xs"><strong>NAME:</strong> {printPreviewInvoice.invoiceFrom?.name}</p>
                      <p className="text-xs"><strong>ADDRESS:</strong> {printPreviewInvoice.invoiceFrom?.address}</p>
                      <p className="text-xs"><strong>MOBILE:</strong> {printPreviewInvoice.invoiceFrom?.mobile}</p>
                    </div>
                    <div className="border-r border-gray-800 p-4">
                      <h3 className="text-xs font-bold mb-2">INVOICE TO</h3>
                      <p className="text-xs"><strong>Customer PIN:</strong> {printPreviewInvoice.customerPRN || 'N/A'}</p>
                      <p className="text-xs"><strong>NAME:</strong> {printPreviewInvoice.customerName.toUpperCase()}</p>
                      <p className="text-xs"><strong>ADDRESS:</strong> {customer?.address || 'N/A'}</p>
                      <p className="text-xs"><strong>MOBILE:</strong> {customer?.contactNumber || 'N/A'}</p>
                    </div>
                    <div className="p-4">
                      <h3 className="text-xs font-bold mb-2">INVOICE NO.</h3>
                      <p className="text-xs"><strong>Invoice:</strong> {printPreviewInvoice.systemInvoiceNumber}</p>
                      <p className="text-xs"><strong>CU Number:</strong> {printPreviewInvoice.manualInvoiceNumber}</p>
                      <p className="text-xs"><strong>Date:</strong> {new Date(printPreviewInvoice.date).toLocaleDateString('en-GB')}</p>
                    </div>
                  </div>

                  {/* Items Table */}
                  <table className="w-full border-collapse border border-gray-800 mb-6">
                    <thead>
                      <tr className="bg-gray-100">
                        <th className="border border-gray-800 p-2 text-xs text-center">S/N</th>
                        <th className="border border-gray-800 p-2 text-xs text-center">Item Description</th>
                        <th className="border border-gray-800 p-2 text-xs text-center">Qty</th>
                        <th className="border border-gray-800 p-2 text-xs text-center">Unit Price</th>
                        <th className="border border-gray-800 p-2 text-xs text-center">Rate</th>
                        <th className="border border-gray-800 p-2 text-xs text-center">Amt incl. Tax</th>
                      </tr>
                    </thead>
                    <tbody>
                      {printPreviewInvoice.items.map((item, index) => (
                        <tr key={index}>
                          <td className="border border-gray-800 p-2 text-xs text-center">{index + 1}</td>
                          <td className="border border-gray-800 p-2 text-xs">{item.itemDescription.toUpperCase()}</td>
                          <td className="border border-gray-800 p-2 text-xs text-center">{formatKenyanNumber(item.quantity, 4)}</td>
                          <td className="border border-gray-800 p-2 text-xs text-center">{formatKenyanNumber(item.unitPrice)}</td>
                          <td className="border border-gray-800 p-2 text-xs text-center">{item.taxRate}%</td>
                          <td className="border border-gray-800 p-2 text-xs text-right">KSh {formatKenyanNumber(item.amountInclTax)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>

                  {/* Tax Summary */}
                  <div className="border border-gray-800 p-4">
                    <p className="font-bold mb-3 text-sm">TAX SUMMARY</p>
                    <table className="w-full">
                      <tr className="bg-gray-100">
                        <th className="border border-gray-800 p-2 text-xs text-center">Tax Rate</th>
                        <th className="border border-gray-800 p-2 text-xs text-center">Taxable Amt</th>
                        <th className="border border-gray-800 p-2 text-xs text-center">Tax Amt</th>
                        <th className="border border-gray-800 p-2 text-xs text-center">Total Amt</th>
                      </tr>
                      <tr>
                        <td className="border border-gray-800 p-2 text-xs text-center">16%</td>
                        <td className="border border-gray-800 p-2 text-xs text-right">KSh {formatKenyanNumber(printPreviewInvoice.taxableTotalAmount)}</td>
                        <td className="border border-gray-800 p-2 text-xs text-right">KSh {formatKenyanNumber(printPreviewInvoice.totalTaxAmount)}</td>
                        <td className="border border-gray-800 p-2 text-xs text-right">KSh {formatKenyanNumber(printPreviewInvoice.totalAmount)}</td>
                      </tr>
                      <tr className="bg-gray-100 font-bold">
                        <td className="border border-gray-800 p-2 text-xs text-center">Totals</td>
                        <td className="border border-gray-800 p-2 text-xs text-right">KSh {formatKenyanNumber(printPreviewInvoice.taxableTotalAmount)}</td>
                        <td className="border border-gray-800 p-2 text-xs text-right">KSh {formatKenyanNumber(printPreviewInvoice.totalTaxAmount)}</td>
                        <td className="border border-gray-800 p-2 text-xs text-right">KSh {formatKenyanNumber(printPreviewInvoice.totalAmount)}</td>
                      </tr>
                    </table>
                  </div>

                  {/* Footer */}
                  <div className="mt-4 text-center text-xs text-gray-600">
                    <p>Powered by Donato Impex Ltd.</p>
                  </div>
                </div>
              </div>

              {/* Modal Footer with Print Button */}
              <div className="flex items-center justify-end gap-3 p-6 border-t border-gray-200 bg-gray-50">
                <button
                  onClick={() => setPrintPreviewInvoice(null)}
                  className="px-6 py-2.5 bg-gray-200 text-gray-700 rounded-lg font-semibold hover:bg-gray-300 transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={() => {
                    handlePrint(printPreviewInvoice);
                    setPrintPreviewInvoice(null);
                  }}
                  className="px-6 py-2.5 bg-emerald-600 text-white rounded-lg font-semibold hover:bg-emerald-700 transition-colors flex items-center gap-2"
                >
                  <Printer className="w-4 h-4" />
                  Print Invoice
                </button>
              </div>
            </div>
          </div>
        );
      })()}
    </div>
  );
}
